version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sbom-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: sbom-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
